version: '3.5'

services:
  main_db:
    image: postgres:17.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=FrenchTool
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=admin123
    volumes:
      - ./pgdata:/var/lib/postgresql/data